import logging
from pathlib import Path

import pandas as pd
from fastapi import APIRouter, HTTPException, Query

logger = logging.getLogger(__name__)


router = APIRouter(
    prefix="/traffic",
    tags=["Traffic"],
)


# ---------------------------------------------------------------------------
# Paths
# ---------------------------------------------------------------------------

PROJECT_ROOT = Path(__file__).resolve().parents[3]

# Precomputed baseline CSV — one observation per traffic-model segment.
# Generated by: python scripts/generate_traffic_baseline.py
# ~6,615 rows, ~670 KB.  Replaces the 795 MB full CSV at runtime.
TRAFFIC_BASELINE_CSV = (
    PROJECT_ROOT
    / "models"
    / "traffic-model"
    / "data"
    / "processed"
    / "synthetic_traffic_baseline.csv"
)

# Full CSV path (preserved for documentation / reference only).
# Training code uses this via config.SYNTHETIC_TRAFFIC_CSV.
_TRAFFIC_FULL_CSV = (
    PROJECT_ROOT
    / "models"
    / "traffic-model"
    / "data"
    / "processed"
    / "synthetic_traffic.csv"
)


# ---------------------------------------------------------------------------
# Cached baseline data
# ---------------------------------------------------------------------------

_baseline_df = None


def load_baseline_data():
    """
    Load the precomputed traffic baseline once.

    The baseline CSV contains exactly one row per traffic-model segment
    (the earliest hourly observation).  It is generated offline from the
    full synthetic_traffic.csv by:

        python scripts/generate_traffic_baseline.csv

    Columns include osm_way_id (pre-derived from road_id).
    """

    global _baseline_df

    if _baseline_df is not None:
        return _baseline_df

    if not TRAFFIC_BASELINE_CSV.exists():
        raise FileNotFoundError(
            f"Traffic baseline not found: {TRAFFIC_BASELINE_CSV}\n"
            f"Generate it with: python scripts/generate_traffic_baseline.py"
        )

    logger.info(
        "Loading traffic baseline from %s ...",
        TRAFFIC_BASELINE_CSV,
    )

    df = pd.read_csv(
        TRAFFIC_BASELINE_CSV,
        dtype={"osm_way_id": str},
    )

    # Ensure timestamp is datetime for consistent .isoformat() output.
    df["timestamp"] = pd.to_datetime(
        df["timestamp"],
        format="mixed",
    )

    _baseline_df = df

    logger.info(
        "Traffic baseline loaded: %d segments, %d OSM ways.",
        len(df),
        df["osm_way_id"].nunique(),
    )

    return _baseline_df


# ---------------------------------------------------------------------------
# Single OSM way baseline
# ---------------------------------------------------------------------------

@router.get("/baseline")
def get_baseline_traffic(
    osm_way_id: str = Query(
        ...,
        description="Original OpenStreetMap way ID",
    )
):
    """
    Return baseline synthetic traffic for one OSM way.

    Multiple traffic-model segments belonging to the same OSM way
    are aggregated together.

    Only the earliest observation of each segment is used.
    """

    try:
        df = load_baseline_data()

    except FileNotFoundError as exc:
        raise HTTPException(
            status_code=500,
            detail=str(exc),
        )

    osm_way_id = str(
        osm_way_id
    ).strip()

    if not osm_way_id.isdigit():
        raise HTTPException(
            status_code=400,
            detail="osm_way_id must contain only digits.",
        )

    # -------------------------------------------------------------------
    # Filter baseline to this OSM way.
    #
    # The baseline already has exactly one row per segment, so no
    # additional groupby/first() is needed.
    # -------------------------------------------------------------------

    road = df[
        df["osm_way_id"] == osm_way_id
    ]

    if road.empty:
        raise HTTPException(
            status_code=404,
            detail=(
                f"No traffic data found for OSM way "
                f"{osm_way_id}"
            ),
        )

    # -------------------------------------------------------------------
    # Aggregate segments belonging to this OSM way.
    # -------------------------------------------------------------------

    traffic_volume = int(
        road["traffic_volume"].sum()
    )

    road_length_m = float(
        road["road_length_m"].sum()
    )

    road_capacity_proxy = float(
        road["road_capacity_proxy"].sum()
    )

    first = road.iloc[0]

    # -------------------------------------------------------------------
    # Congestion.
    # -------------------------------------------------------------------

    congestion_ratio = (
        traffic_volume
        / max(road_capacity_proxy, 1.0)
    )

    congestion_percent = (
        congestion_ratio * 100.0
    )

    return {
        "osm_way_id": int(osm_way_id),

        "timestamp": first["timestamp"].isoformat(),

        "segment_count": int(
            len(road)
        ),

        "traffic_volume": traffic_volume,

        "road_type": first["road_type"],

        "road_name": first["road_name"],

        "road_length_m": round(
            road_length_m,
            1,
        ),

        "lane_count": int(
            first["lane_count"]
        ),

        "speed_limit_kmh": float(
            first["speed_limit_kmh"]
        ),

        "is_oneway": bool(
            first["is_oneway"]
        ),

        "is_bridge": bool(
            first["is_bridge"]
        ),

        "is_tunnel": bool(
            first["is_tunnel"]
        ),

        "road_capacity_proxy": round(
            road_capacity_proxy,
            1,
        ),

        "intersection_density": float(
            first["intersection_density"]
        ),

        "node_degree": int(
            first["node_degree"]
        ),

        "connected_road_count": int(
            first["connected_road_count"]
        ),

        "road_hierarchy": first[
            "road_hierarchy"
        ],

        "congestion_ratio": round(
            congestion_ratio,
            6,
        ),

        "congestion_percent": round(
            congestion_percent,
            4,
        ),

        "data_type": "synthetic",
    }


# ---------------------------------------------------------------------------
# All baseline traffic
# ---------------------------------------------------------------------------

@router.get("/baseline/all")
def get_all_baseline_traffic():
    """
    Return baseline synthetic traffic aggregated by OSM way.

    The precomputed baseline CSV contains exactly one row per
    traffic-model segment (the earliest hourly observation).

    We aggregate those segments back to their original OSM way.

    This produces one baseline record per OSM way.
    """

    try:
        df = load_baseline_data()

    except FileNotFoundError as exc:
        raise HTTPException(
            status_code=500,
            detail=str(exc),
        )

    if df.empty:
        return {
            "timestamp": None,
            "data_type": "synthetic",
            "roads": [],
        }

    # -------------------------------------------------------------------
    # Aggregate traffic-model segments to OSM way.
    # -------------------------------------------------------------------

    grouped = (
        df
        .groupby(
            "osm_way_id",
            as_index=False,
        )
        .agg(
            traffic_volume=(
                "traffic_volume",
                "sum",
            ),

            road_capacity_proxy=(
                "road_capacity_proxy",
                "sum",
            ),

            segment_count=(
                "road_id",
                "count",
            ),
        )
    )

    # -------------------------------------------------------------------
    # Calculate congestion.
    # -------------------------------------------------------------------

    grouped[
        "congestion_ratio"
    ] = (
        grouped["traffic_volume"]
        / grouped[
            "road_capacity_proxy"
        ].clip(lower=1)
    )

    grouped[
        "congestion_percent"
    ] = (
        grouped[
            "congestion_ratio"
        ] * 100
    )

    # -------------------------------------------------------------------
    # Use the earliest baseline timestamp.
    # -------------------------------------------------------------------

    timestamp = df[
        "timestamp"
    ].min()

    return {
        "timestamp": timestamp.isoformat(),

        "data_type": "synthetic",

        "roads": grouped.to_dict(
            orient="records"
        ),
    }
